name: ci-docker-releases

on:
  push:
    branches: [ "releases/**" ]
  pull_request:
    branches: [ "releases/**" ]
jobs:
  build-push:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Display build info
        run: echo ${{ github.actor }}, ${{ github.env }}, ${{ github.ref }}

      - name: "Set current date as env variable"
        run: |
          echo "buildyear=$(date +'%Y')" >> $GITHUB_ENV
          echo "builddate=$(date +'%m%d%H%M')" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: ${{ secrets.DOCKERHUB_REPO }}:latest, ${{ secrets.DOCKERHUB_REPO }}:v6-${{ env.buildyear }}-${{ env.builddate }}